[Interface]
PrivateKey = yFB8WNT7mn88Hs9vQfZG+zBjMjdPpL3sMCM9d21YE2c=
Address = 10.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = iw4JoFP4TJfILedNKoq56JTJqHG53S21yiM6/ckic2g=
Endpoint = 35.179.161.45:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
